baseURL = "https://smartpetbuys.pages.dev/"
languageCode = "en-us"
title = "SmartPetBuys"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "auto"
  description  = "Smart choices for your pets — reviews, guides, and deals."
  mainSections = ["posts"]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowWordCount = true
  ShowFullTextinRSS = true
  # SEO improvements
  keywords = ["pet products", "dog supplies", "cat accessories", "pet reviews"]
  author = "SmartPetBuys Team"
  # Logo for schema markup
  logo = "/images/smartpetbuys_logo.png"

[params.homeInfoParams]
  Title = "Smart choices for your pets"
  Content = "Independent reviews, buying guides, and deals — updated automatically."

[params.profileMode]
  enabled = false

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2