baseURL = "https://smartpetbuys.pages.dev/"
languageCode = "en-us"
title = "SmartPetBuys"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "auto"
  description  = "Smart choices for your pets — reviews, guides, and deals."
  mainSections = ["posts"]

[params.homeInfoParams]
  Title = "Smart choices for your pets"
  Content = "Independent reviews, buying guides, and deals — updated automatically."

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2