baseURL = "https://www.smartpetbuys.com/"
languageCode = "en-us"
title = "SmartPetBuys - Expert Pet Product Reviews & Buying Guides"
theme = "PaperMod"

# Enable sitemap generation
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  page = ["HTML"]

# Sitemap configuration
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# Enable robots.txt
[outputFormats]
  [outputFormats.robots]
    mediaType = "text/plain"
    baseName = "robots"
    isPlainText = true
    notAlternative = true

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "auto"
  description  = "Expert pet product reviews, buying guides, and deals. Find the best dog food, cat toys, pet beds, and more with our comprehensive testing and recommendations."
  mainSections = ["posts"]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowWordCount = true
  ShowFullTextinRSS = true
  
  # Enhanced SEO
  keywords = ["pet products", "dog supplies", "cat accessories", "pet reviews", "best pet products", "dog food reviews", "cat toys", "pet beds", "pet health", "pet care"]
  author = "SmartPetBuys Team"
  logo = "/images/smartpetbuys_logo.png"
  
  # Social media
  twitter = "@smartpetbuys"
  facebook = "smartpetbuys"
  instagram = "smartpetbuys"
  
  # Contact information for schema
  contact = "contact@smartpetbuys.com"
  phone = ""
  address = ""
  
  # Favicon
  favicon = "/favicon.ico"
  
  # Business hours for schema
  businessHours = "Monday-Friday 9AM-6PM EST"
  
  # Enable search
  enableSearch = true
  
  # Performance
  enableFingerprinting = true
  enableMinify = true

[params.ga4]
  id = "G-HHVQX4ENNP"

[params.homeInfoParams]
  Title = "Smart Choices for Your Pets 🐾"
  Content = "Discover the best products for your furry friends with our expert reviews, detailed buying guides, and unbeatable deals. From premium dog food to cozy cat beds — we've tested it all so you don't have to."

[params.profileMode]
  enabled = false

[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]

# Taxonomies for better organization
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
    
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 3
    
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/legal/about/"
    weight = 4