
# This workflow is a placeholder based on Handoff.MD.
# 1. Add your OPENAI_API_KEY to GitHub > Settings > Secrets > Actions.
# 2. Fill keywords.csv with keywords and set 'publish' to 'yes'.
name: 'Auto Publish Content'

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 14 * * 1-5' # Runs at 14:00 UTC on weekdays

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit changes back to the repo
    steps:
      - name: 'Clear Git Cache'
        run: |
          git config --global --unset-all http.https://github.com/.extraheader || true
          git config --global --unset-all http.proxy || true

      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 1

      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 'Install Dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install openai frontmatter

      - name: 'Generate New Content'
        id: generate
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "🤖 Starting content generation..."
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "❌ ERROR: OPENAI_API_KEY not found in secrets"
            exit 1
          fi
          echo "✅ OpenAI API key detected"
          echo "📊 Checking keywords.csv for publishable content..."
          python scripts/generate_single_post.py
          echo "✅ Content generation completed."
        continue-on-error: false

      - name: 'Validate Hugo Build'
        run: |
          echo "Installing Hugo..."
          wget -O hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.120.4/hugo_extended_0.120.4_Linux-64bit.tar.gz
          tar -xzf hugo.tar.gz
          sudo mv hugo /usr/local/bin/
          echo "Testing Hugo build..."
          hugo --minify --destination public_test
          echo "Hugo build successful!"

      - name: 'Commit and Push Changes'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add content/posts/
          git add IMPROVEMENT_ACTION_PLAN.md || true
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "✅ No new content generated. Nothing to commit."
            echo "This might mean:"
            echo "  - No keywords marked 'publish=yes' in keywords.csv"
            echo "  - All keywords already have 3 posts (spam prevention)"
            echo "  - OpenAI API error occurred"
          else
            echo "📝 New content detected. Committing changes..."
            git commit -m "$(cat <<'EOF'
Content: Add new AI-generated blog post

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>
EOF
)"
            echo "🚀 Pushing to repository..."
            git push
            echo "✅ Content published successfully!"
          fi
