
# This workflow is a placeholder based on Handoff.MD.
# 1. Add your OPENAI_API_KEY to GitHub > Settings > Secrets > Actions.
# 2. Fill keywords.csv with keywords and set 'publish' to 'yes'.
name: 'Auto Publish Content'

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 14 * * 1-5' # Runs at 14:00 UTC on weekdays

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit changes back to the repo
    steps:
      - name: 'Clear Git Cache'
        run: |
          git config --global --unset-all http.https://github.com/.extraheader
          git config --global --unset-all http.proxy

      - name: 'Checkout Repository'
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 1

      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 'Install Dependencies'
        run: |
          python -m pip install --upgrade pip
          # pip install openai # Uncomment when ready

      - name: 'Generate New Content'
        id: generate
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/generate_post.py

      - name: 'Commit and Push Changes'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add content/posts/
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No new content generated. Nothing to commit."
          else
            git commit -m "Content: Add new AI-generated posts"
            git push
          fi
